# Generated by Django 5.1.7 on 2025-06-19 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moda_app', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
